# Generated by Django 5.0.3 on 2024-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название формата битвы')),
            ],
            options={
                'verbose_name': 'Формат битвы',
                'verbose_name_plural': 'Форматы битвы',
            },
        ),
        migrations.CreateModel(
            name='BattleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название типа события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа события')),
                ('event_type', models.CharField(choices=[('BS-0', 'BS-0'), ('BS-1', 'BS-1'), ('BS-2', 'BS-2'), ('BS-3', 'BS-3'), ('BS-4', 'BS-4'), ('BS-5', 'BS-5'), ('BS-6', 'BS-6'), ('BS-7', 'BS-7'), ('BS-8', 'BS-8'), ('BS-9', 'BS-9'), ('BS-10', 'BS-10')], default='BS-0', max_length=5, verbose_name='Тип события')),
                ('can_be_series', models.BooleanField(default=False, verbose_name='Могут объединяться в серии')),
                ('can_be_league', models.BooleanField(default=False, verbose_name='Могут объединяться в лигу')),
                ('can_be_festival', models.BooleanField(default=False, verbose_name='Могут объединяться в фестиваль')),
            ],
            options={
                'verbose_name': 'Тип битвы',
                'verbose_name_plural': 'Типы битв - СТИХИИ',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=0, verbose_name='Уровень координатора')),
            ],
            options={
                'verbose_name': 'Координатор',
                'verbose_name_plural': 'Координаторы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Точный адрес')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('Запланировано', 'Запланировано'), ('Активно', 'Активно'), ('Завершено', 'Завершено')], max_length=20, verbose_name='Статус события')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активное')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название типа события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа события')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фестиваля')),
            ],
            options={
                'verbose_name': 'Фестиваль',
                'verbose_name_plural': 'Фестивали',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лиги')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждение участия')),
            ],
            options={
                'verbose_name': 'Участники в событии',
                'verbose_name_plural': 'Участники в событиях',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('description', models.TextField(verbose_name='Описание роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название серии')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
