# Generated by Django 5.0.3 on 2024-03-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_events', to='events.coordinator', verbose_name='Координатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='event_helpers', to=settings.AUTH_USER_MODEL, verbose_name='Помощники организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype', verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='festival',
            name='battle_types',
            field=models.ManyToManyField(related_name='festivals', to='events.battletype', verbose_name='Типы битв, входящие в фестиваль'),
        ),
        migrations.AddField(
            model_name='league',
            name='battle_types',
            field=models.ManyToManyField(related_name='leagues', to='events.battletype', verbose_name='Типы битв, входящие в лигу'),
        ),
        migrations.AddField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='participation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.role', verbose_name='Роль участника в событии'),
        ),
        migrations.AddField(
            model_name='series',
            name='battle_types',
            field=models.ManyToManyField(related_name='series', to='events.battletype', verbose_name='Типы битв, входящие в серию'),
        ),
        migrations.CreateModel(
            name='ElementalBattle',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('gathering_time', models.TimeField(default='18:30', verbose_name='Время сбора на битву')),
                ('photographer', models.BooleanField(default=False, verbose_name='Наличие фотографа')),
                ('rated_game', models.BooleanField(default=False, verbose_name='Рейтинговая игра')),
                ('battle_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.battleformat', verbose_name='Формат битвы')),
                ('battle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.battletype', verbose_name='Тип битвы')),
            ],
            options={
                'verbose_name': 'Битва стихий',
                'verbose_name_plural': 'Битвы стихий',
            },
            bases=('events.event',),
        ),
    ]
