# Generated by Django 5.0.3 on 2024-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='battle_types',
        ),
        migrations.RemoveField(
            model_name='league',
            name='battle_types',
        ),
        migrations.RemoveField(
            model_name='series',
            name='battle_types',
        ),
        migrations.AddField(
            model_name='festival',
            name='events',
            field=models.ManyToManyField(related_name='festivals', to='events.event', verbose_name='События в фестивале'),
        ),
        migrations.AddField(
            model_name='festival',
            name='leagues',
            field=models.ManyToManyField(related_name='festivals', to='events.league', verbose_name='Лиги в фестивале'),
        ),
        migrations.AddField(
            model_name='festival',
            name='series',
            field=models.ManyToManyField(related_name='festivals', to='events.series', verbose_name='Серии в фестивале'),
        ),
        migrations.AddField(
            model_name='league',
            name='events',
            field=models.ManyToManyField(related_name='leagues', to='events.event', verbose_name='События в лиге'),
        ),
        migrations.AddField(
            model_name='league',
            name='series',
            field=models.ManyToManyField(related_name='leagues', to='events.series', verbose_name='Серии в лиге'),
        ),
        migrations.AddField(
            model_name='series',
            name='events',
            field=models.ManyToManyField(related_name='series', to='events.event', verbose_name='События в серии'),
        ),
        migrations.AlterField(
            model_name='battletype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='battletype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название события'),
        ),
    ]
