# Generated by Django 5.0.3 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_festival_battle_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='battletype',
            name='event_type',
            field=models.CharField(choices=[('BS-0', 'BS-0'), ('BS-1', 'BS-1'), ('BS-2', 'BS-2'), ('BS-3', 'BS-3'), ('BS-4', 'BS-4'), ('BS-5', 'BS-5'), ('BS-6', 'BS-6')], default='BS-0', max_length=5, verbose_name='Тип события'),
        ),
    ]
