# Generated by Django 5.0.3 on 2024-03-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_type_alter_battletype_event_type'),
        ('users', '0003_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_events', to='users.coordinator', verbose_name='Координатор'),
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
