# Generated by Django 5.0.3 on 2024-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_coordinator_delete_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementalbattle',
            name='gathering_time',
            field=models.TimeField(default='0:30', verbose_name='Время сбора на битву'),
        ),
    ]
