# Generated by Django 5.0.3 on 2024-03-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_elementalbattle_gathering_time'),
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='event_helpers', to='users.profile', verbose_name='Помощники организатора'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='users.profile', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь'),
        ),
    ]
