# Generated by Django 5.0.3 on 2024-03-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_description_alter_event_organizer_and_more'),
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='organized_events', to='users.profile', verbose_name='Организатор'),
        ),
    ]
