# Generated by Django 5.0.3 on 2024-03-29 06:55

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_organizer'),
        ('users', '0010_coordinator_city_travel_coordinator_country_travel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=events.models.get_system_organizer_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='organized_events', to='users.profile', verbose_name='Организатор'),
        ),
    ]
