# Generated by Django 5.0.3 on 2024-03-30 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_end_time'),
        ('users', '0010_coordinator_city_travel_coordinator_country_travel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_events', to='users.coordinator', verbose_name='Координатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('active', 'Активно'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус события'),
        ),
    ]
