# Generated by Django 5.0.3 on 2024-04-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_coordinator_alter_event_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
