# Generated by Django 5.0.3 on 2024-04-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_delete_location'),
        ('main', '0006_alter_city_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city_conn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='event',
            name='country_conn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
