# Generated by Django 5.0.3 on 2024-04-12 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_city_conn_event_country_conn'),
        ('main', '0006_alter_city_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city_conn',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country_conn',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
