# Generated by Django 5.0.3 on 2024-04-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_event_city_conn_remove_event_country_conn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='event',
            name='country_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
    ]
