# Generated by Django 5.0.3 on 2024-04-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_city_text_event_country_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country_text',
        ),
    ]
