# Generated by Django 5.0.3 on 2024-04-13 06:13

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_event_city_text_remove_event_country_text'),
        ('users', '0014_remove_coordinator_city_conn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(blank=True, default=events.models.get_system_organizer_default, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='coordinated_events', to='users.coordinator', verbose_name='Координатор'),
        ),
    ]
