# Generated by Django 5.0.3 on 2024-04-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_coordinator'),
        ('users', '0015_remove_coordinator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_events', to='users.coordinator', verbose_name='Координатор'),
        ),
    ]
