# Generated by Django 5.0.3 on 2024-03-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Введите название которе будет отображаться в системе', max_length=255, null=True, verbose_name='Название проекта')),
                ('system_organizer', models.IntegerField(blank=True, default=1, help_text='Например после удаление организатора события, будет указан он в качестве организатора', verbose_name='Системный организатор')),
                ('cache', models.IntegerField(blank=True, default=0, help_text='Указать число в секундах', verbose_name='Кеширование')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
