# Generated by Django 5.0.3 on 2024-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='system_organizer',
            field=models.IntegerField(blank=True, default=1, help_text='Например после удаление организатора события, будет указан он в качестве организатора', verbose_name='Системный организатор - ID'),
        ),
    ]
