# Generated by Django 5.0.3 on 2024-04-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='countryCode',
            new_name='country_code',
        ),
    ]
