# Generated by Django 5.0.3 on 2024-04-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countryCode',
            new_name='country_code',
        ),
    ]
