# Generated by Django 5.0.3 on 2024-04-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_countrycode_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_code',
            field=models.CharField(max_length=255),
        ),
    ]
