# Generated by Django 5.0.3 on 2024-03-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_coordinator_username_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language Code'),
        ),
    ]
