# Generated by Django 5.0.3 on 2024-03-23 10:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_coordinator_city_coordinator_country_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
