# Generated by Django 5.0.3 on 2024-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_coordinator_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='city_travel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город - расположение'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='country_travel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна - расположение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_travel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город - расположение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_travel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна - расположение'),
        ),
    ]
