# Generated by Django 5.0.3 on 2024-04-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0010_coordinator_city_travel_coordinator_country_travel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='country_conn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_conn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
