# Generated by Django 5.0.3 on 2024-04-11 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0011_coordinator_country_conn_profile_country_conn'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='city_conn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_conn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
