# Generated by Django 5.0.3 on 2024-04-12 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0013_alter_coordinator_username_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='city_conn',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='country_conn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_conn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country_conn',
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
    ]
