# Generated by Django 5.0.3 on 2024-04-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_coordinator_city_conn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='user',
        ),
    ]
