# Generated by Django 5.0.3 on 2024-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_coordinator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='city_travel',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='country_travel',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='Координатор'),
        ),
    ]
