# Generated by Django 5.0.3 on 2024-04-14 09:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0017_coordinator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_coordinator',
        ),
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_travel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город - расположение'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_travel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна - расположение'),
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.BooleanField(default=False, verbose_name='Идентификация'),
        ),
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
