# Generated by Django 5.0.3 on 2024-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0020_alter_user_city_alter_user_country_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='coordinators', to='main.city'),
        ),
    ]
