# Generated by Django 5.0.3 on 2024-04-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0021_coordinator_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coordinator')),
            ],
        ),
    ]
