# Generated by Django 5.0.3 on 2024-04-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_country_code'),
        ('users', '0022_coordinatorcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorcity',
            name='city',
        ),
        migrations.AddField(
            model_name='coordinatorcity',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='coordinators_city', to='main.city'),
        ),
    ]
