# Generated by Django 5.0.3 on 2024-04-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_coordinatorcity_city_coordinatorcity_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoordinatorCity',
        ),
    ]
